[[data]]
gregorian = '2013-06-21'
"lunar tithi" = '??-13'
vikrama = '2070'

[[data]]
gregorian = '2013-12-22'
"lunar tithi" = '??-20'
vikrama = '2070'

[[data]]
gregorian = '2014-06-21'
"lunar tithi" = '??-24'
vikrama = '2071'

[[data]]
gregorian = '2014-12-22'
"lunar tithi" = '10-30 (अधिकः)'
vikrama = '2071'

[[data]]
gregorian = '2015-06-22'
"lunar tithi" = '05-06'
vikrama = '2072'

[[data]]
gregorian = '2015-12-22'
"lunar tithi" = '11-12'
vikrama = '2072'

[[data]]
gregorian = '2016-06-21'
"lunar tithi" = '05-16'
vikrama = '2073'

[[data]]
gregorian = '2016-12-21'
"lunar tithi" = '11-23'
vikrama = '2073'

[[data]]
gregorian = '2017-06-21'
"lunar tithi" = '04-27 (अधिकः)'
vikrama = '2074'

[[data]]
gregorian = '2017-12-22'
"lunar tithi" = '11-04'
vikrama = '2074'

[[data]]
gregorian = '2018-06-21'
"lunar tithi" = '05-09'
vikrama = '2075'

[[data]]
gregorian = '2018-12-22'
"lunar tithi" = '11-15'
vikrama = '2075'

[[data]]
gregorian = '2019-06-22'
"lunar tithi" = '05-20'
vikrama = '2076'

[[data]]
gregorian = '2019-12-22'
"lunar tithi" = '10-26 (अधिकः)'
vikrama = '2076'

[[data]]
gregorian = '2020-06-21'
"lunar tithi" = '04-30 (नाधिकः! गतायनारम्भे ऽधिकमासात्।)'
vikrama = '2077'

[[data]]
gregorian = '2020-12-21'
"lunar tithi" = '11-07'
vikrama = '2077'

[[data]]
gregorian = '2021-06-21'
"lunar tithi" = '2078)'
vikrama = '2078'

[[data]]
gregorian = '2021-12-22'
"lunar tithi" = '11-18'
vikrama = '2078'

[[data]]
gregorian = '2022-06-22'
"lunar tithi" = '05-23'
vikrama = '2079'

[[data]]
gregorian = '2022-12-22'
"lunar tithi" = '10-28 (अधिकः)'
vikrama = '2079'
